---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: library-app
  namespace: default
  labels:
    app: library-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-app
  template:
    metadata:
      labels:
        app: library-app
    spec:
      containers:
      - name: library-app
        image: "balat2020/library-app:latest"
        ports:
          - containerPort: 5000
        volumeMounts:
          - name: sqlite-storage
            mountPath: /app/db  # Mount path inside the container (SQLite db will be here)
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: sqlite-pvc
            
---
apiVersion: v1
kind: Service
metadata:
  name: library-app
  namespace: default
spec:
  selector:
    app: library-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 5000
    port: 80
