apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlite-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/library.db  # Local path for SQLite database
  persistentVolumeReclaimPolicy: Retain  # Retain the data after the pod is deleted
  storageClassName: standard
